const mongoose=require('mongoose')
const courseSchema=new mongoose.Schema({
    Section_Id:{
        type:[mongoose.Schema.Types.ObjectId],
        ref:'Section'
    },
    Title:{
        type:String,
        unique:true,
        required:true
    },
    Description:{
        type:String,
        required:true
    },
    Rating:{
        type:[Number],
        minimum:0,
        maximum:5,
        default:0
    },
    Reviews:{
        type:[mongoose.Schema.Types.ObjectId],
        ref:'Review'
    },
    Category_Id:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Categories'
    },
    Price:{
        type:String,
        required:true
    },
    Language:{
        type:[String],
        required:true
    },
    Level:{
        type:String,
        enum:['beginner','intermediate','advanced'],
        required:true
    },
    Category:{
        type:[String],
        required:true
    }
})
module.exports=mongoose.model('Courses',courseSchema)